spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 22606808ZHS
    url: jdbc:mysql://127.0.0.1:3306/ms?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    rabbitmq: guest
    virtual-host: /
    #\u6D88\u8D39\u8005\u6570\u91CF
    listener.simple.concurrency: 10
    listener.simple.max-concurrency: 10
    #\u6D88\u8D39\u8005\u6BCF\u6B21\u4ECE\u961F\u5217\u83B7\u53D6\u7684\u6D88\u606F\u6570\u91CF
    listener.simple.prefetch: 1
    #\u6D88\u8D39\u8005\u81EA\u52A8\u542F\u52A8
    listener.simple.auto-startup: true
    listener.simple.acknowledge-mode: manual
    #\u6D88\u8D39\u5931\u8D25\uFF0C\u81EA\u52A8\u91CD\u65B0\u5165\u961F
    listener.simple.default-requeue-rejected: true
    #\u542F\u7528\u53D1\u9001\u91CD\u8BD5
    template.retry.enabled: true
    template.retry.initial-interval: 1000
    template.retry.max-attempts: 3
    template.retry.max-interval: 10000
    template.retry.multiplier: 1.0
#server.servlet.context-path: /miaosha
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration.map-underscore-to-camel-case: true
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  timeout: 10
  poolMaxTotal: 100
  poolMaxIdle: 50